### ISSUE TITLE
Node Editor Full Screen disables node interaction

### ISSUE THREAD

**Issue by chainke** [jblattgerste/TrainAR#7]
When entering the full screen mode of the node editor via double click, the node editor does not react to interactions anymore. E.g. new transitions or moving nodes is not possible anymore, as well as clicking buttons in the interface. 
Current solution: Click "TrainAR -> Open TrainAR Editor" to reset the editor windows.

**Comment by jblattgerste** [comment]
I cannot reproduce this, but as we hook deeply into the Unity Visual Scripting package for this, I expect it's a package or Unity version bug. I updated both.
